import { useState } from "react";
import { useRouter } from "next/router";
import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Mail, Lock } from "lucide-react";

export default function LoginPage() {
  const [email, setEmail] = useState("");
  const [password, setPassword] = useState("");
  const router = useRouter();

  const handleLogin = () => {
    if (email && password) {
      router.push("/dashboard");
    } else {
      alert("Vui lòng nhập email và mật khẩu");
    }
  };

  return (
    <div className="flex items-center justify-center h-screen bg-gray-100">
      <Card className="w-96 p-6 shadow-lg rounded-2xl bg-white">
        <CardContent>
          <h2 className="text-xl font-bold text-center mb-4">Đăng nhập</h2>
          <div className="space-y-4">
            <div>
              <Label>Email</Label>
              <div className="relative">
                <Mail className="absolute left-2 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <Input
                  type="email"
                  placeholder="Nhập email"
                  value={email}
                  onChange={(e) => setEmail(e.target.value)}
                  className="pl-8"
                />
              </div>
            </div>
            <div>
              <Label>Mật khẩu</Label>
              <div className="relative">
                <Lock className="absolute left-2 top-1/2 transform -translate-y-1/2 text-gray-400" />
                <Input
                  type="password"
                  placeholder="Nhập mật khẩu"
                  value={password}
                  onChange={(e) => setPassword(e.target.value)}
                  className="pl-8"
                />
              </div>
            </div>
            <Button className="w-full bg-blue-600 text-white" onClick={handleLogin}>
              Đăng nhập
            </Button>
            <div className="text-center text-sm text-gray-500">Hoặc</div>
            <Button variant="outline" className="w-full">Đăng nhập với Google</Button>
            <Button variant="outline" className="w-full">Đăng nhập với Microsoft</Button>
          </div>
        </CardContent>
      </Card>
    </div>
  );
}
